# Generated by Django 5.0 on 2025-10-02 14:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('current_status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('SECURITY_CLEARED', 'Security Cleared'), ('LOADED', 'Loaded'), ('IN_FLIGHT', 'In-Flight'), ('ARRIVED', 'Arrived')], default='CHECKED_IN', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Baggage',
                'verbose_name_plural': 'Baggage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('SECURITY_CLEARED', 'Security Cleared'), ('LOADED', 'Loaded'), ('IN_FLIGHT', 'In-Flight'), ('ARRIVED', 'Arrived')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='tracking.baggage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Update',
                'verbose_name_plural': 'Status Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('PASSENGER', 'Passenger'), ('ADMIN', 'Admin')], default='PASSENGER', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
